name       :  imap
version    : 2007f
release    : 5
source     :
    - ftp://ftp.cac.washington.edu/mail/imap.tar.Z : 870e95f6bd19265832a88fd89b77c54c841c59022fd21e69254050c8b1005e3c
license    : Apache 2.0
summary    : IMAP is a method of accessing electronic messages kept on a mail server.
description: |
    IMAP (Internet Message Access Protocol) is a method of accessing electronic messages kept on a (possibly shared) mail server.
builddeps  :
  - pkgconfig(libssl)
  - pam-devel
patterns:
    - [/usr/bin, /usr/lib64, /etc]
    - devel :
      - /usr/include/imap
build      : |
    %patch -p1 < $pkgfiles/c-client-2006k_GENTOO_amd64-so-fix.patch
    %make lnp SSLTYPE=unix.nopwd PASSWDTYPE=pam SPECIALAUTHENTICATORS=ssl SSLINCLUDE=/usr/include/openssl/ \
    EXTRACFLAGS="${CFLAGS} -fPIC -lcom_err -lpam"
install    : |
    install -d $installdir/usr/bin
    install -d $installdir/usr/include
    install -d $installdir/%libdir%
    install -d $installdir/etc/ssl/certs
    install -d $installdir/etc/xinetd.d/imap
    install -d $installdir/etc/xinetd.d/ipop2
    install -d $installdir/etc/xinetd.d/ipop3

    # Binary Copying

    install -D -m755 dmail/dmail $installdir/usr/bin/dmail
    install -D -m755 imapd/imapd $installdir/usr/bin/imapd
    install -D -m755 ipopd/ipop2d $installdir/usr/bin/ipop2d
    install -D -m755 ipopd/ipop3d $installdir/usr/bin/ipop3d
    install -D -m755 mailutil/mailutil $installdir/usr/bin/mailutil

    # Shared Object Copying and Symlinking

    install -D -m755 c-client/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so.1.0.0
    ln -sf $installdir/%libdir%/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so.1
    ln -sf $installdir/%libdir%/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so

    # Generate SSL PEMs for secure(r) imap

    for i in imapd ipop3d; do
        PEM1=$installdir/pem1
        PEM2=$installdir/pem2
        cat  $pkgfiles/keyprops | /usr/bin/openssl req -newkey rsa:4096 -keyout $PEM1 -nodes -x509 -days 365 -out  $PEM2

        cat $PEM1 >  ${i}.pem
        echo ""    >> ${i}.pem
        cat $PEM2 >> ${i}.pem
        rm $PEM1 $PEM2
        umask 022
    done

    install -D -m600 imapd.pem $installdir/etc/ssl/certs/imapd.pem
    install -D -m600 ipop3d.pem $installdir/etc/ssl/certs/ipop3d.pem

    # Install xinetd.d configs

    install -D -m644 $pkgfiles/xinetd.d/imap $installdir/etc/xinetd.d/imap
    install -D -m644 $pkgfiles/xinetd.d/ipop2 $installdir/etc/xinetd.d/ipop2
    install -D -m644 $pkgfiles/xinetd.d/ipop3 $installdir/etc/xinetd.d/ipop3

    # Copy the headers from individual directories over to the imap includes

    for i in c-client mail imap4r1 rfc822 linkage misc smtp nntp \
        osdep env_unix env fs ftl nl tcp sslio utf8 utf8aux; do
        install -D -m644 c-client/${i}.h $installdir/usr/include/imap/${i}.h
    done

    # Shared lib. Required by PHP.

    install -D -m644 c-client/c-client.a $installdir/%libdir%/c-client.a
    ln -sf $installdir/%libdir%/c-client.a $installdir/%libdir%/libc-client.a

    make clean
