name       :  imap
version    : 2007f
release    : 3
source     :
    - ftp://ftp.cac.washington.edu/mail/imap.tar.Z : 870e95f6bd19265832a88fd89b77c54c841c59022fd21e69254050c8b1005e3c
license    : Apache 2.0
summary    : IMAP is a method of accessing electronic messages kept on a mail server.
description: |
    IMAP (Internet Message Access Protocol) is a method of accessing electronic messages kept on a (possibly shared) mail server.
builddeps  :
  - pkgconfig(libssl)
  - pam-devel
patterns:
    - [/usr/bin, /usr/lib64]
    - devel :
      - /usr/include/imap
build      : |
    %patch -p1 < $pkgfiles/c-client-2006k_GENTOO_amd64-so-fix.patch
    %make lnp SSLTYPE=unix.nopwd PASSWDTYPE=pam SPECIALAUTHENTICATORS=ssl SSLINCLUDE=/usr/include/openssl/ \
    EXTRACFLAGS="${CFLAGS} -fPIC -lcom_err -lpam"
install    : |
    install -d $installdir/usr/bin
    install -d $installdir/usr/include
    install -d $installdir/%libdir%

    install -D -m755 dmail/dmail $installdir/usr/bin/dmail
    install -D -m755 imapd/imapd $installdir/usr/bin/imapd
    install -D -m755 ipopd/ipop2d $installdir/usr/bin/ipop2d
    install -D -m755 ipopd/ipop3d $installdir/usr/bin/ipop3d
    install -D -m755 mailutil/mailutil $installdir/usr/bin/mailutil

    install -D -m755 c-client/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so.1.0.0
    ln -sf $installdir/%libdir%/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so.1
    ln -sf $installdir/%libdir%/libc-client.so.1.0.0 $installdir/%libdir%/libc-client.so

    for i in c-client mail imap4r1 rfc822 linkage misc smtp nntp \
        osdep env_unix env fs ftl nl tcp sslio utf8 utf8aux; do
        install -D -m644 c-client/${i}.h $installdir/usr/include/imap/${i}.h
    done

    make clean
